### PR TITLE
clean-1

### PR DESCRIPTION
**Pull request by nomad-cc20**
Code cleaned of pointless comments, added Polynome constructor, extracted several methods, added parameter handling and variable names got revised.

### CODE REVIEW

**Comment by bLuma** [comment]
Please separate classes to individual files before merging, this looks like a big mess. TY

**Review by bLuma — CHANGES_REQUESTED** [review]
Make separate files for different classes.

**Comment by nomad-cc20** [comment]
Ok, classes are now separated.

**Review by bLuma — APPROVED** [review]

**Comment by bLuma** [comment]
Ok. Accepted.

**Pull request closed without merging**
